<a href="https://colab.research.google.com/github/sirisha5e1/rajavathsirisha/blob/main/assignments/100_Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
import numpy as np
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
import numpy as np
x=np.array([100,20,34])
print("Size of the array:",x.size)
print("Memory size of one array element in bytes:",x.itemsize)
print("Memory size of numpy array in bytes:",x.size*x.itemsize)

Size of the array: 3
Memory size of one array element in bytes: 8
Memory size of numpy array in bytes: 24


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
import numpy as np
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [ ]:
import numpy as np

np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [ ]:
import numpy as np
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
import numpy as np
x=np.zeros(10, dtype=int)
if x[5]==0:
    x[5]=1
print(x)

[0 0 0 0 0 1 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
import numpy as np
z=np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
import numpy as np
y=np.arange(80)
y= y[::-1]
print(y)

[79 78 77 76 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56
 55 54 53 52 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32
 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8
  7  6  5  4  3  2  1  0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
x=np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
s=np.nonzero([1,2,0,0,4,0])
print(s)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
N=np.eye(3)
print(N)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
Y=np.random.random((3,3,3))
print(Y)

[[[0.48523097 0.18341068 0.29979325]
  [0.63693108 0.09893667 0.5645059 ]
  [0.51337593 0.97926452 0.67170157]]

 [[0.89736825 0.84821374 0.58637236]
  [0.9975923  0.28924881 0.49975974]
  [0.7603205  0.80648898 0.16439241]]

 [[0.95840713 0.32114745 0.1269969 ]
  [0.67519661 0.17285845 0.95410554]
  [0.05233453 0.26989649 0.84412231]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
X=np.random.random((10,10))
Xmin,Xmax=X.min(),X.max()
print(Xmin,Xmax)

0.018211297891301825 0.9951977912737847


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
y=np.random.random(30)
m=y.mean()
print(m)

0.46227387432006245


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a=np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
import numpy as np
A= np.ones((8,8))
A=np.pad(A, pad_width=1, mode='constant',constant_values=0)
print(A)
A[:,[0,-1]] = 0
A[[0,-1], :] = 0
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan==np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
X=np.diag(1+np.arange(4),k=-1)
print(X)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
M=np.zeros((8,8),dtype=int)
M[1::2,::2] =1
M[::2,1::2] =1
print(M)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
import numpy as np
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
import numpy as np
X= np.tile(np.array([[0,1], [1,0]]), (4,4))
print (X)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
T=np.random.random((5,5))
T=(T-np.mean(T))/(np.std(T))
print(T)

[[ 0.75200116 -0.29016148  1.15286159  0.38683424  0.59295412]
 [ 0.80938376 -0.69860263  0.64084323  1.14407453  0.06237241]
 [-1.81256972  1.16891705 -0.3815059   0.70918673  0.60675894]
 [-0.44850182 -1.46105238 -1.79390694  1.15376602  0.086602  ]
 [ 1.10160505 -0.89922416 -1.48031814 -1.61682485  0.51450717]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
import numpy as np
color = np.dtype([("r",np.ubyte),
                  ("g",np.ubyte),
                  ("b",np.ubyte),
                  ("a",np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
A=np.dot(np.ones((5,3)), np.ones((3,2)))
print(A)
A=np.ones((5,3)) @ np.ones((3,2))
print(A)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
D=np.arange(11)
D[(3<D)&(D<=8)]*=-1
print(D)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [24]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


<ipython-input-24-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
<ipython-input-24-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
<ipython-input-24-2a10de0ee61b>:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [29]:
Z= np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-3. -8.  3. -9. -4.  8.  2. -3. -1. -2.]
[-3. -8.  3. -9. -4.  8.  2. -3. -1. -2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [33]:
A1=np.random.randint(0,200,200)
A2=np.random.randint(0,200,200)
print(np.intersect1d(A1,A2))

[  0   2   3   4   5   8   9  12  14  18  19  22  24  29  35  37  40  41
  43  44  46  49  52  54  56  57  58  60  64  69  73  74  75  76  77  84
  87  89  91  92  93  98 100 102 105 109 110 112 113 114 118 122 125 126
 127 129 130 133 139 140 142 143 145 148 151 158 159 161 162 163 164 165
 168 172 177 182 184 185 190 195 199]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [34]:
defaults = np.seterr(all="ignore")
X=np.ones(1)/0
np.seterr(**defaults)
with np.errstate(all="ignore"):
    np.arange(3)/0
    X=np.arange(3)/0
    print(X)

[nan inf inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [38]:
import numpy as np
np.sqrt(-1)==np.emath.sqrt(-1)
np.sqrt(-1)==np.emath.sqrt(-1)

<ipython-input-38-5295bc09d449>:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)==np.emath.sqrt(-1)
<ipython-input-38-5295bc09d449>:3: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1)==np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [43]:
import numpy as np
yesterday=np.datetime64('today')-np.timedelta64(1)
today=np.datetime64('today')
tomorrow=np.datetime64('today')+np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2024-11-25
2024-11-26
2024-11-27


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [45]:
L=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(L)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [46]:
X=np.ones(5)*2
Y=np.ones(5)*3
np.add(X,Y,out=Y)
np.divide(X,2,out=X)
np.negative(X,out=X)
np.multiply(X,Y,out=X)

array([-5., -5., -5., -5., -5.])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [48]:
  K=np.random.uniform(0,50,70)
  print(K-K%1)
  print(np.floor(K))
  print(np.ceil(K)-1)
  print(K.astype(int))
  print(np.trunc(K))

[17. 11.  9. 44. 29.  2. 10. 42. 12. 34. 21. 47. 41.  8. 14.  0. 21. 45.
 23. 49. 29. 29.  7. 26. 39. 28. 10. 30. 30.  1. 21. 24. 38. 18. 27.  6.
 48.  7. 48. 35. 11. 34. 36. 37. 29. 26. 22.  5. 11. 26. 18. 31. 31. 32.
 44. 30. 16. 40. 19. 18. 37.  0. 44.  7. 23. 30. 25.  2. 40. 33.]
[17. 11.  9. 44. 29.  2. 10. 42. 12. 34. 21. 47. 41.  8. 14.  0. 21. 45.
 23. 49. 29. 29.  7. 26. 39. 28. 10. 30. 30.  1. 21. 24. 38. 18. 27.  6.
 48.  7. 48. 35. 11. 34. 36. 37. 29. 26. 22.  5. 11. 26. 18. 31. 31. 32.
 44. 30. 16. 40. 19. 18. 37.  0. 44.  7. 23. 30. 25.  2. 40. 33.]
[17. 11.  9. 44. 29.  2. 10. 42. 12. 34. 21. 47. 41.  8. 14.  0. 21. 45.
 23. 49. 29. 29.  7. 26. 39. 28. 10. 30. 30.  1. 21. 24. 38. 18. 27.  6.
 48.  7. 48. 35. 11. 34. 36. 37. 29. 26. 22.  5. 11. 26. 18. 31. 31. 32.
 44. 30. 16. 40. 19. 18. 37.  0. 44.  7. 23. 30. 25.  2. 40. 33.]
[17 11  9 44 29  2 10 42 12 34 21 47 41  8 14  0 21 45 23 49 29 29  7 26
 39 28 10 30 30  1 21 24 38 18 27  6 48  7 48 35 11 34 36 37 29 26 22  5

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [49]:
Y=np.zeros((5,5))
Y+=np.arange(5)
print(Y)
Y=np.tile(np.arange(0,5),(5,1))
print(Y)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [54]:
def generate():
  for y in range(10):
    yield y
x=np.fromiter(generate(),dtype=float,count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [58]:
Q=np.linspace(0,1,11,endpoint=False)[1:]
print(Q)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [59]:
N=np.random.random(10)
N.sort()
print(N)

[0.00142621 0.0774551  0.13654384 0.18321147 0.45138606 0.48345925
 0.49517152 0.5875271  0.80746749 0.99121408]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [60]:
B=np.arange(230)
np.add.reduce(B)

26335

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [61]:
A=np.random.randint(0,6,15)
B=np.random.randint(0,6,15)
equal=np.allclose(A,B)
print(equal)
equal=np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [67]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X*2+Y*2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.2771354  1.26183864 1.24260751 1.53423086 1.51038285 1.39307695
 0.93026274 1.59941421 1.63912578 1.78197291]
[0.48423335 1.41209055 0.1346687  1.31945463 0.2980912  0.67360297
 0.82923889 0.68097957 0.78145524 1.0274302 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [68]:
A=np.random.random(10)
A[A.argmax()]=0
print(A)

[0.57948962 0.11323612 0.82137492 0.74235068 0.07352726 0.12608544
 0.17500569 0.10248786 0.         0.29406723]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [70]:
Z = np.zeros((7,7), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,7),
                             np.linspace(0,1,7))
print(Z)

[[(0.        , 0.        ) (0.16666667, 0.        )
  (0.33333333, 0.        ) (0.5       , 0.        )
  (0.66666667, 0.        ) (0.83333333, 0.        )
  (1.        , 0.        )]
 [(0.        , 0.16666667) (0.16666667, 0.16666667)
  (0.33333333, 0.16666667) (0.5       , 0.16666667)
  (0.66666667, 0.16666667) (0.83333333, 0.16666667)
  (1.        , 0.16666667)]
 [(0.        , 0.33333333) (0.16666667, 0.33333333)
  (0.33333333, 0.33333333) (0.5       , 0.33333333)
  (0.66666667, 0.33333333) (0.83333333, 0.33333333)
  (1.        , 0.33333333)]
 [(0.        , 0.5       ) (0.16666667, 0.5       )
  (0.33333333, 0.5       ) (0.5       , 0.5       )
  (0.66666667, 0.5       ) (0.83333333, 0.5       )
  (1.        , 0.5       )]
 [(0.        , 0.66666667) (0.16666667, 0.66666667)
  (0.33333333, 0.66666667) (0.5       , 0.66666667)
  (0.66666667, 0.66666667) (0.83333333, 0.66666667)
  (1.        , 0.66666667)]
 [(0.        , 0.83333333) (0.16666667, 0.83333333)
  (0.33333333, 0.83333333) (

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [71]:
A=np.arange(16)
B=A+0.8
C=1.0/np.subtract.outer(A,B)
print(np.linalg.det(C))


17887483823.583435


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [75]:
import numpy as np
for dtype in[np.int8,np.int32,np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in[np.float32,float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [79]:
import numpy as np
np.set_printoptions(threshold=float("inf"))
P=np.zeros((60,30))
print(P)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [80]:
S=np.arange(350)
v=np.random.uniform(0,350)
index=(np.abs(S-v)).argmin()
print(S[index])

288


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [100]:
import numpy as np
A = np.random.randint(0,5,(10,3))
print(A)
U=A[np.all(A[:,1:]==A[:,:-1],axis=1)]
print(U)
U=A[A.max(axis=1)!=A.min(axis=1),:]
print(U)

[[0 2 2]
 [3 4 3]
 [0 2 3]
 [0 4 2]
 [4 0 3]
 [4 3 2]
 [1 3 1]
 [4 0 2]
 [1 0 4]
 [4 1 1]]
[]
[[0 2 2]
 [3 4 3]
 [0 2 3]
 [0 4 2]
 [4 0 3]
 [4 3 2]
 [1 3 1]
 [4 0 2]
 [1 0 4]
 [4 1 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [92]:

I=np.array([0,1,2,3,15,16,32,64,128],dtype=np.uint8)
print(np.unpackbits(I[:,np.newaxis],axis=1))
I=np.array([0, 1, 2, 3, 15, 16, 32, 64, 128],dtype=np.uint8)
print(np.unpackbits(I[:,np.newaxis],axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [89]:
A=np.random.randint(0,4,(12,6))
T=np.ascontiguousarray(A).view(np.dtype((np.void,A.dtype.itemsize*A.shape[1])))
_,idx=np.unique(T,return_index=True)
uZ=A[idx]
print(uZ)

[[0 2 0 0 3 3]
 [0 2 1 3 1 2]
 [0 2 3 0 2 0]
 [0 2 3 3 1 2]
 [0 3 1 3 0 3]
 [1 0 1 1 0 3]
 [1 2 1 0 3 2]
 [1 3 0 1 3 2]
 [1 3 0 2 3 0]
 [2 2 3 0 0 1]
 [2 3 2 1 3 2]
 [3 3 3 2 0 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [88]:
X=np.random.uniform(0,2,20)
Y=np.random.uniform(0,2,20)
np.einsum('i->',X)
np.einsum('i,i->i',X,Y)
np.einsum('i,i',X,Y)
np.einsum('i,j->ij',X,Y)

array([[3.11117099e-01, 1.73482871e-01, 3.12931743e-02, 1.60747708e-01,
        2.70073268e-02, 1.71718326e-01, 3.22491858e-01, 5.52552522e-01,
        3.66277942e-01, 5.55511066e-01, 3.48034834e-01, 1.62419940e-01,
        6.94428505e-01, 7.63901039e-02, 5.01844479e-01, 5.59622501e-01,
        5.89086950e-01, 2.61361377e-01, 4.85712793e-01, 5.73014583e-02],
       [1.04478519e+00, 5.82585575e-01, 1.05087908e-01, 5.39818691e-01,
        9.06952887e-02, 5.76659927e-01, 1.08298360e+00, 1.85556722e+00,
        1.23002487e+00, 1.86550253e+00, 1.16876135e+00, 5.45434333e-01,
        2.33201139e+00, 2.56531221e-01, 1.68528082e+00, 1.87930944e+00,
        1.97825617e+00, 8.77696843e-01, 1.63110782e+00, 1.92428238e-01],
       [6.09476606e-01, 3.39851945e-01, 6.13031483e-02, 3.14903835e-01,
        5.29071978e-02, 3.36395212e-01, 6.31759693e-01, 1.08244721e+00,
        7.17536379e-01, 1.08824298e+00, 6.81798237e-01, 3.18179727e-01,
        1.36038144e+00, 1.49647774e-01, 9.83110446e-01, 1.0962

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [87]:
phi=np.arange(0,10*np.pi,0.1)
a=1
x=a*phi*np.cos(phi)
y=a*phi*np.sin(phi)
dr=(np.diff(x)**2+np.diff(y)**2)**.5
r=np.zeros_like(x)
r[1:]=np.cumsum(dr)
r_int=np.linspace(0,r.max(),200)
x_int=np.interp(r_int,r,x)
y_int=np.interp(r_int,r,y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [85]:
X=np.asarray([[1.0, 0.0, 3.0, 8.0],
[2.0, 0.0, 1.0, 1.0],
[1.5,2.5,1.0,0.0]])
n=4
M=np.logical_and.reduce(np.mod(X,1)==0,axis=-1)
M&=(X.sum(axis=-1)==n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [84]:
import numpy as np
import scipy.stats as st
np.random.seed(10)
X=np.random.randn(100)
N=1000
idx=np.random.randint(0,X.size,(N,X.size))
means=X[idx].mean(axis=1)
confint=np.percentile(means,[2.5,97.5])
print(confint)


[-0.11779332  0.25754188]
